configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
install:
- cinst dotnetcore
before_build:
- appveyor-retry dotnet restore "src"
build_script:
- dotnet build "src" -c %CONFIGURATION%
test_script:
- dotnet test "test" -c %CONFIGURATION%
cache:
- '%USERPROFILE%\.nuget\packages'